---
layout: cv
title: Jason Chandler's CV
---
# Jason Chandler


<div id="webaddress">
<a href="https://www.linkedin.com/in/jason-chandler3/">https://www.linkedin.com/in/jason-chandler3/</a>
</div>


## Currently

Student at BYUI

### Specialized in

Embedded systems and Machine Learning

## Education

`2020-2026`
__Brigham Young University - Idaho__



## Occupation

`June 2025 – August 2025`
__Software Engineer Intern__,
Honeywell Inc

* IOT Data Integration and Production Information Visualization – Provide production information visualization
across cells via integration of PLC, Ignition and Python.

* Software Source Code Documentation – Create documentation (flow chart, notation, etc.) of an In-House MES
system, allow easy maintenance, troubleshooting, and expandability.

* Project Management Platform Implementation for Engineering Team – Collaborate with IT for the
implementation of Jira to provide task ticketing portal, transparent project status and workload management.

* New Product Implementation Project Support – support the NPI project including PFMEA, application
deployment, Trial-Run and Release.

* Quality Improvement Project Support – support root cause analysis, experiment design and validation for resolving a quality
complained incident.

`January 2025 – April 2025`
__Teching Assistant__,Brigham Young University - Idaho

* Evaluated and provided feedback on students' program designs and implementations to enhance their coding
skills and problem-solving abilities.

* Improved course materials by updating lecture content to include a language-selection feature for programming
examples, highlighting the advantages and trade-offs of different languages.
Computer Systems Tutor June 2024 – July 2024
Brigham Young University - Idaho

* Guided students through the troubleshooting processes of Labs that involved Arduino Peripherals and libraries
as they started becoming familiar with embedded systems.



<!-- ### Footer

Last updated: May 2013 -->